version: '3.8'
services: 
    nginx:
        image: 'apollo-nginx'
        build:
            context: ./services/nginx
            dockerfile: ./Dockerfile
        container_name: apollo-nginx
        depends_on:
            - gateway
            - userservice
            - bookingservice
            - chatservice
            - redisCommander
        hostname: nginx
        ports:
            - 80:80
    gateway: 
        image: gateway
        container_name: apollo-gateway
        build: 
            context: .
            dockerfile: ./deploy/gateway/Dockerfile
        ports: 
            - 3000:3000
        depends_on:
            - userservice
            - bookingservice
            - chatservice
        hostname: gateway
    userservice:
        image: user-service
        container_name: apollo-userservice
        build: 
            context: .
            dockerfile: ./deploy/user/Dockerfile
        hostname: userservice
        depends_on: 
            - userservice-db
        ports: 
            - 3001:3000
        env_file: 
            - ./.env
    userservice-db:
        image: 'mongo:4.4'
        container_name: userservice-db
        restart: always
        env_file: 
           - ./.env
    bookingservice:
        image: booking-service
        container_name: apollo-bookingservice
        build: 
            context: .
            dockerfile: ./deploy/booking/Dockerfile
        hostname: bookingservice
        depends_on: 
            - bookingservice-db
            - redis
        env_file: 
            - ./.env
    bookingservice-db:
        image: 'mongo:4.4'
        container_name: bookingservice-db
        restart: always
        env_file: 
           - ./.env
    chatservice:
        image: chat-service
        container_name: apollo-chatservice
        build: 
            context: .
            dockerfile: ./deploy/chat/Dockerfile
        hostname: chatservice
        depends_on: 
            - chatservice-db
            - redis
        env_file: 
            - ./.env
    chatservice-db:
        image: 'rethinkdb:2.4.1'
        container_name: chatservice-db
        restart: always
        ports:
          - 8080:8080   
        env_file: 
           - ./.env
    redis:
        image: 'redis'
        container_name: apollo-redis
        # ports: 
        #     - "6379:6379"
  
    redisCommander:
        image: 'rediscommander/redis-commander'
        container_name: apollo-rediscommander
        depends_on:
          - redis
        env_file: 
         -  ./.env
        ports:
          - "8081:8081"    
        